[project]
name = "sal"
version = "1.2.5"
description = "Simple Access Layer (SAL) is a data access middleware and storage system, focused on storing scientific data for large experiments."
authors = [
	{name = "Alex Meakins", email = "alex.meakins@ukaea.uk"}
]
license = {text = "EUPL v1.2"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
	"numpy>=1.19.2",
	"requests>=2.14.2",
	"importlib-metadata>=6.7.0",
]

[project.optional-dependencies]
LDAP = [ "ldap3>=2.8.1" ]
server = [
	"flask>=0.12.2, <2.0",
	# flask-restful broken for flask>=3 as of flask-restful 0.3.10
	# as flask>=3 requires werkzeug>=3
	# https://github.com/flask-restful/flask-restful/issues/963
	"flask-restful>=0.3.8",
	# upper constraint on itsdangerous and Jinja2 required by Flask<1.1.3
	# Flask>=1.1.3 enforces these constraints
	# both constraints can be removed if dependency changed to Flask>=1.1.3
	"itsdangerous>=1.1.0, <2.0",
	"Jinja2<3.0",
	# MarkupSafe constraint required for Jinja2
	# required by Flask
	# should be removed when moving to Flask>=2
	"MarkupSafe<2.0",
]

[project.urls]
Homepage = "https://github.com/simpleaccesslayer"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pylint = "^2.6.0"
pytest = "^6.2.2"
hypothesis = "^6.1.1"
