[project]
name = "sal"
version = "1.2.5"
description = "Simple Access Layer (SAL) is a data access middleware and storage system, focused on storing scientific data for large experiments."
authors = [
	{name = "Alex Meakins", email = "alex.meakins@ukaea.uk"}
]
license = {text = "EUPL v1.2"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
	"flask>=0.12.2",
	"flask-restful>=0.3.8",
	"numpy>=1.19.2",
	"requests>=2.14.2",
	"itsdangerous>=1.1.0",
	"importlib-metadata>=6.7.0"
]

[project.optional-dependencies]
LDAP = [ "ldap3>=2.8.1" ]

[project.urls]
Homepage = "https://github.com/simpleaccesslayer"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pylint = "^2.6.0"
pytest = "^6.2.2"
hypothesis = "^6.1.1"
